config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :production_processes, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :new, :show, :create, :show, :edit, :update]
    resources :workers, only: [:index, :show, :edit, :update]
    resources :progresses, only: [:index, :show, :edit, :update]
    get 'worker_index/:id' => 'progresses#worker_index', as: 'worker_index' #従業員実績履歴
  end

  #従業員用
  devise_for :worker,skip: [:passwords], controllers: {
    registrations: "worker/registrations",
    sessions: 'worker/sessions'
  }
  scope module: :worker do
    resources :workers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :show]
    resources :progresses, only: [:show, :create, :edit, :update]

    patch 'progresses/:id/start' => 'progresses#start', as: 'progresses_start' #商品開始
    patch 'progresses/:id/finish' => 'progresses#finish', as: 'progresses_finish' #商品終了
    get 'worker_index/:id' => 'progresses#worker_index', as: 'worker_index' #従業員実績履歴
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :progresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, length: { minimum: 1, maximum: 20 }
  validates :first_name, length: { minimum: 1, maximum: 20 }

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/workers_controller.rb
class Admin::WorkersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @workers = Worker.page(params[:page])
  end

  def show
    @worker = Worker.find(params[:id])
    @progresses = @worker.progresses
    #一時間当たり生産量の平均
    @average = Progress.average_count(@worker.id)

    @today_progress = @progresses.created_today
    @yesterday_progress = @progresses.created_yesterday
    @this_week_progress = @progresses.created_this_week
    @last_week_progress = @progresses.created_last_week
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])
    if @worker.update(workers_params)
      redirect_to admin_worker_path(@worker), notice: '従業員情報を更新しました'
    else
      redirect_to edit_admin_worker_path(@worker), alert: '従業員情報の更新に失敗しました'
    end
  end

  private

  def workers_params
    params.require(:worker).permit(:first_name, :last_name, :email, :is_deleted)
  end
end

app/controllers/worker/confirmations_controller.rb
# frozen_string_literal: true

class Worker::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/worker/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Worker::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/worker/passwords_controller.rb
# frozen_string_literal: true

class Worker::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/worker/products_controller.rb
class Worker::ProductsController < ApplicationController
  before_action :authenticate_worker!
  def index
    @products = Product.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
    @progress = Progress.new
  end
end

app/controllers/worker/progresses_controller.rb
class Worker::ProgressesController < ApplicationController
  before_action :authenticate_worker!
  before_action :ensure_correct_worker, only: [:edit, :update]

  def create
    @progress = Progress.new(progress_params)
    @progress.worker_id = current_worker.id
    if @progress.save
      redirect_to edit_progress_path(@progress), notice: 'タイマーを開始してください'
    else
      redirect_to products_path, alert: '部数を入力してください'
    end
  end

  def edit
    @progress = Progress.find(params[:id])
  end

  def update
    @progress = Progress.find(params[:id])
    if @progress.update(progress_params)
      if @progress.end_time != nil
        redirect_to progress_path(@progress), notice: '実績を更新しました'
      else
        redirect_to edit_progress_path(@progress),notice: '部数の変更をしました'
      end
    else
      redirect_to edit_progress_path(@progress), alert: '実績の更新に失敗しました'
    end
  end

  def start
    @progress = Progress.find(params[:id])
    @progress.begin_time = DateTime.now
    @progress.save
    redirect_to edit_progress_path(@progress), notice: 'タイマーが開始されました'
  end

  def finish
    @progress = Progress.find(params[:id])
    @progress.end_time = DateTime.now
    @progress.save
    redirect_to progress_path(@progress.id), notice: '実績が登録されました'
  end

  def index
    @progresses = Progress.page(params[:page])
  end

  def show
    @progress = Progress.find(params[:id])
  end

  def worker_index
    @worker = Worker.find(params[:id])
    @progresses = @worker.progresses.page(params[:page]).order(end_time: "DESC")
  end

  private

  def progress_params
    params.require(:progress).permit(:product_id, :worker_id, :product_count, :begin_time, :end_time)
  end

  #自分の実績のみ編集可能
  def ensure_correct_worker
    @progress = Progress.find(params[:id])
    unless @progress.worker == current_worker
      redirect_to worker_path(current_worker)
    end
  end

end

app/controllers/worker/registrations_controller.rb
# frozen_string_literal: true

class Worker::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
     worker_path(current_worker)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name])
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/worker/sessions_controller.rb
# frozen_string_literal: true

class Worker::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    worker_path(current_worker)
  end

  def after_sign_out_path_for(resource)
    new_worker_session_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/worker/unlocks_controller.rb
# frozen_string_literal: true

class Worker::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/worker/workers_controller.rb
class Worker::WorkersController < ApplicationController
  before_action :authenticate_worker!
  before_action :ensure_correct_worker, only: [:edit, :update]

  def index
    @workers = Worker.page(params[:page])
  end

  def show
    @worker = Worker.find(params[:id])
    @progresses = @worker.progresses
    #一時間当たり生産量の平均
    @average = Progress.average_count(@worker.id)

    @today_progress = @progresses.created_today
    @yesterday_progress = @progresses.created_yesterday
    @this_week_progress = @progresses.created_this_week
    @last_week_progress = @progresses.created_last_week
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])
    if @worker.update(workers_params)
      redirect_to worker_path(@worker), notice: '従業員情報を更新しました。'
    else
      redirect_to edit_worker_path(@worker), alert: '従業員情報の更新に失敗しました'
    end
  end

  private

  def workers_params
    params.require(:worker).permit(:first_name, :last_name, :email)
  end

  #自分の従業員情報のみ編集可能
  def ensure_correct_worker
    @worker = Worker.find(params[:id])
    unless @worker == current_worker
      redirect_to worker_path(current_worker)
    end
  end
end

app/helpers/admin/workers_helper.rb
module Admin::WorkersHelper
end

app/helpers/worker/homes_helper.rb
module Worker::HomesHelper
end

app/helpers/worker/products_helper.rb
module Worker::ProductsHelper
end

app/helpers/worker/progresses_helper.rb
module Worker::ProgressesHelper
end

app/helpers/worker/workers_helper.rb
module Worker::WorkersHelper
end

app/views/admin/workers/_info.html.erb
<table class ="table" id="worker-table">
  <tbody>
    <tr>
      <th>従業員名</th>
      <td><%= worker.last_name %> <%= worker.first_name %></td>
    </tr>
    <tr>
      <th>ID</th>
      <td><%= worker.id %></td>
    </tr>
    <tr>
      <th>平均部数(/h)</th>
      <td><%= average.to_i %>　部/(h)</td>
    </tr>
    <tr>
      <th>ステータス</th>
        <% if worker.is_deleted == false %>
          <td class="text-success">有効</td>
        <% elsif %>
          <td class="text-danger">退会</td>
        <% end %>
    </tr>
  </tbody>
</table>

<div class='row'>
  <%= link_to  edit_admin_worker_path(worker), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <%end%>

  <%= link_to '実績', admin_worker_index_path(worker), class: 'btn btn-success my-3' %>
</div>

app/views/admin/workers/edit.html.erb
<div class="container">
  <div class="row">
    <h3 class="m-3 bg-light">
      <%= @worker.last_name %><%= @worker.first_name %>さんの情報編集画面
    </h3>
  </div>
  <%= form_with model: [:admin,@worker] do |f| %>
    <div class="field row">
      <div class="col-xl-2 mx-auto"><%= f.label :worker_id, "会員ID" %></div>
      <div class="col-xl-6 mx-auto"><%= @worker.id %></div>
    </div>
    <div class="field row">
      <div class="col-xl-2 mx-auto"><%= f.label :name, "氏名" %></div>
      <div class="col-xl-6 mx-auto form-inline">
        <%= f.text_field :last_name, class: "form-control mr-2 mb-2" %>
        <%= f.text_field :first_name, class: "form-control mb-2" %>
      </div>
    </div>

    <div class="field row">
      <div class="col-xl-2 mx-auto"><%= f.label :email, "メールアドレス" %></div>
      <div class="col-xl-6 mx-auto"><%= f.email_field :email, autocomplete: "email", class: "form-control mb-2" %></div>
    </div>

    <div class="field row">
      <div class="col-xl-2 mx-auto"><%= f.label :is_deleted, "会員ステータス" %></div>
      <div class="col-xl-6 mx-auto">
        <%= f.radio_button :is_deleted, true %>
        <%= f.label :is_deleted, "退会", value: true %>
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted, "有効", value: false %>
       </div>
    </div>
    <div class="field row">
      <div class="col-xl-2 mx-auto"></div>
      <div class="col-xl-6 mx-auto mb-5 mt-3"><%= f.submit "変更を保存", class: "btn btn-success" %></div>
    </div>
  <% end %>
</div>

app/views/admin/workers/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="ml-3 my-5 bg-light">従業員一覧</h3>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-10">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>ID</th>
            <th>名前</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @workers.each do |worker| %>
        <tbody>
          <tr>
            <td><%= worker.id %></td>
            <td>
              <%= link_to admin_worker_path(worker.id) do%>
                <%= worker.last_name %> <%= worker.first_name %>
              <%end%>
            </td>
              <% if worker.is_deleted == false %>
                <td class="text-success">有効</td>
              <% elsif %>
                <td class="text-danger">退会</td>
              <% end %>
          </tr>
        </tbody>
        <% end %>
      </table>
      <div class="row justify-content-center">
        <%= paginate @workers %>
      </div>
    </div>
  </div>
</div>

app/views/admin/workers/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h3 class="my-5 bg-light">従業員詳細</h3>
      <%= render 'info', worker: @worker, average: @average %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <%= render 'worker/progress-count/weak-chart', progresses: @progresses %>
      <h3 class="my-5 bg-light">件数の前日比・前週比</h3>
      <%= render 'worker/progress-count/day-count', today_progress: @today_progress, yesterday_progress: @yesterday_progress %>
      <%= render 'worker/progress-count/weak-count', this_week_progress: @this_week_progress, last_week_progress: @last_week_progress %>
    </div>
  </div>
</div>