config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :production_processes, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :new, :show, :create, :show, :edit, :update]
    resources :workers, only: [:index, :show, :edit, :update]
    resources :progresses, only: [:index, :show, :edit, :update]
    get 'worker_index/:id' => 'progresses#worker_index', as: 'worker_index' #従業員実績履歴
  end

  #従業員用
  devise_for :worker,skip: [:passwords], controllers: {
    registrations: "worker/registrations",
    sessions: 'worker/sessions'
  }
  scope module: :worker do
    resources :workers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :show]
    resources :progresses, only: [:show, :create, :edit, :update]

    patch 'progresses/:id/start' => 'progresses#start', as: 'progresses_start' #商品開始
    patch 'progresses/:id/finish' => 'progresses#finish', as: 'progresses_finish' #商品終了
    get 'worker_index/:id' => 'progresses#worker_index', as: 'worker_index' #従業員実績履歴
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :progresses, dependent: :destroy
  belongs_to :production_process

  validates :production_process_id, presence: true
  validates :name, presence: true
  validates :introduction, length: { minimum: 1, maximum: 200 }
end

app/models/production_process.rb
class ProductionProcess < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, length: { minimum: 1, maximum: 30 }
end

app/models/progress.rb
class Progress < ApplicationRecord
  belongs_to :worker
  belongs_to :product

  validates :product_count, presence: true

  def time_diff
    if end_time != nil
      (end_time - begin_time) / 60 / 60
    end
  end

  #一時間当たりの生産量の計算
  def count_per_hour
    product_count / time_diff
  end

  #一時間当たり生産量の平均
  def self.average_count(worker_id)
    product_counts = 0
    total_time = 0
    Worker.find(worker_id).progresses.find_each do |progress|
      if progress.end_time != nil
        product_counts += progress.product_count
        total_time += progress.time_diff
      end
    end
    product_counts / total_time
  rescue ZeroDivisionError
      0
  end

  scope :created_today, -> { where(end_time: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(end_time: 1.day.ago.all_day) } # 前日
  scope :created_2day_ago, -> { where(end_time: 2.day.ago.all_day) } # 2日前
  scope :created_3day_ago, -> { where(end_time: 3.day.ago.all_day) } # 3日前
  scope :created_4day_ago, -> { where(end_time: 4.day.ago.all_day) } # 4日前
  scope :created_5day_ago, -> { where(end_time: 5.day.ago.all_day) } # 5日前
  scope :created_6day_ago, -> { where(end_time: 6.day.ago.all_day) } # 6日前

  scope :created_this_week, -> { where(end_time: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } #今週
  scope :created_last_week, -> { where(end_time: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } # 前週
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :progresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, length: { minimum: 1, maximum: 20 }
  validates :first_name, length: { minimum: 1, maximum: 20 }

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @product = Product.new
    @processes = ProductionProcess.all
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to admin_product_path(@product), notice: "商品 #{@product.name} を登録しました。"
    else
      redirect_to new_admin_product_path, alert: "未入力の項目があるか、文字数が多すぎます"
    end
  end

  def index
    @products = Product.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @processes = ProductionProcess.all
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(products_params)
      redirect_to admin_product_path(@product), notice: '商品情報を更新しました'
    else
      redirect_to edit_admin_product_path(@product), alert: '更新に失敗しました'
    end
  end

  private

  def products_params
    params.require(:product).permit(:production_process_id, :name, :introduction)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    admin_progresses_path
  end

  def after_sign_out_path_for(resource)
    admin_session_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/workers_controller.rb
class Admin::WorkersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @workers = Worker.page(params[:page])
  end

  def show
    @worker = Worker.find(params[:id])
    @progresses = @worker.progresses
    #一時間当たり生産量の平均
    @average = Progress.average_count(@worker.id)

    @today_progress = @progresses.created_today
    @yesterday_progress = @progresses.created_yesterday
    @this_week_progress = @progresses.created_this_week
    @last_week_progress = @progresses.created_last_week
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])
    if @worker.update(workers_params)
      redirect_to admin_worker_path(@worker), notice: '従業員情報を更新しました'
    else
      redirect_to edit_admin_worker_path(@worker), alert: '従業員情報の更新に失敗しました'
    end
  end

  private

  def workers_params
    params.require(:worker).permit(:first_name, :last_name, :email, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/progresses_helper.rb
module Admin::ProgressesHelper
end

app/helpers/admin/workers_helper.rb
module Admin::WorkersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/worker/homes_helper.rb
module Worker::HomesHelper
end

app/helpers/worker/products_helper.rb
module Worker::ProductsHelper
end

app/helpers/worker/progresses_helper.rb
module Worker::ProgressesHelper
end

app/helpers/worker/workers_helper.rb
module Worker::WorkersHelper
end

app/views/admin/progress-count/_day-count.html.erb
<div class = "table_width">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>今日の実績</th>
        <th>前日の実績</th>
        <th>前日比</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= today_progress.count %>件</td>
        <td><%= yesterday_progress.count %>件</td>
    　   <td>
          <% if yesterday_progress.count == 0 %>
            前日の実績はありません
          <% else %>
       　    <% @the_day_before =   @today_progress.count / @yesterday_progress.count.to_f  %>
       　    <%= (@the_day_before * 100).round %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/progress-count/_weak-chart.html.erb
<h3 class="my-5 bg-light">7日間分の件数</h3>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>６日前</th>
        <th>５日前</th>
        <th>４日前</th>
        <th>３日前</th>
        <th>２日前</th>
        <th>１日前</th>
        <th>今日</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @progresses.created_6day_ago.count %></td>
        <td><%= @progresses.created_5day_ago.count %></td>
        <td><%= @progresses.created_4day_ago.count %></td>
        <td><%= @progresses.created_3day_ago.count %></td>
        <td><%= @progresses.created_2day_ago.count %></td>
        <td><%= @progresses.created_yesterday.count %></td>
        <td><%= @progresses.created_today.count %></td>
      </tr>
    </tbody>
  </table>
  <canvas id="myLineChart"></canvas>
  <script>
    $(document).ready(function() {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '件数',
              data: [
                <%= @progresses.created_6day_ago.count %>,
                <%= @progresses.created_5day_ago.count %>,
                <%= @progresses.created_4day_ago.count %>,
                <%= @progresses.created_3day_ago.count %>,
                <%= @progresses.created_2day_ago.count %>,
                <%= @progresses.created_yesterday.count %>,
                <%= @progresses.created_today.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の件数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>

app/views/admin/progress-count/_weak-count.html.erb
<div class="table_width">
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>今週の実績件数</th>
        <th>前週の実績件数</th>
        <th>前週比</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= this_week_progress.count %>件</td>
        <td><%= last_week_progress.count %>件</td>
        <td>
          <% if last_week_progress.count == 0 %>
            前週の実績が0のため計算できません
          <% else %>
            <% @the_week_before = @this_week_progress.count / @last_week_progress.count.to_f  %>
            <%= (@the_week_before * 100).round %>%
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success shadow-sm">
    <div class="container">
      <a class="navbar-brand" href="/"><strong>workwork recorder</strong></a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_progresses_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-history"></i> 実績一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_products_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-layer-group"></i> 商品一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_production_processes_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-industry"></i> 工程一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_workers_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-users"></i> 従業員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
          <% elsif worker_signed_in? %>
            <p class="text-white mr-2 my-auto text-nowrap"><small></small><%= current_worker.last_name %><%= current_worker.first_name %><small></small></p>
            <li class="nav-item">
              <%= link_to worker_path(current_worker.id), class: "nav-link text-light text-nowrap btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-user-circle"></i> マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to worker_index_path(current_worker.id), class: "nav-link text-light text-nowrap btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-history"></i> 実績一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to products_path, class: "nav-link text-light text-nowrap btn btn-outline-success mr-1 mb-1" do %>
                 <i class="fas fa-layer-group"></i> 商品一覧
              <% end %>
            </li>
              <li class="nav-item">
              <%= link_to workers_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-users"></i> 従業員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_worker_session_path, method: :delete, class:"nav-link text-light text-nowrap btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
          <% else %>

            <li class="nav-item">
              <%= link_to new_worker_registration_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_worker_session_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_session_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-sign-in-alt"></i> 管理者ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/_notice.html.erb
<% if notice %>
 <p id="notice" class="alert alert-success m-0 text-center"><%= notice %></p>
<% end %>

<% if alert%>
  <p id="notice" class="alert alert-danger m-0 text-center"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Work</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <hearder>
        <%= render 'layouts/header' %>
      </hearder>

      <main>
        <div id="flash-success">
          <%=render "layouts/notice" %>
        </div>
        <%= yield %>
      </main>

      <footer>
        <div class="py-4 bg-success text-center">
          <div class="container">
            <p class="text-white small">&copy; 2022 workwork recorder</p>
          </div>
        </div>
      </footer>
    </div>
  </body>

</html>